"""Sample test — auto-generated by goal."""

from __future__ import annotations

from types import SimpleNamespace

from planfile import Planfile
from planfile.analysis.sprint_generator import SprintGenerator
import pytest


def test_placeholder():
    """Placeholder test to verify the test setup works."""
    assert True


def test_import():
    """Verify the main package can be imported."""
    assert True


def test_planfile_bulk_ticket_creation_is_capped(monkeypatch):
    pf = object.__new__(Planfile)
    created = []

    def fake_create_ticket(**kwargs):
        created.append(kwargs)
        return SimpleNamespace(**kwargs)

    monkeypatch.setattr(pf, 'create_ticket', fake_create_ticket)
    tickets = [{"title": f"Ticket {i}", "priority": "high"} for i in range(Planfile.MAX_BULK_TICKETS + 10)]

    result = pf.create_tickets_bulk(tickets, source="goal", sprint="current")

    assert len(result) == Planfile.MAX_BULK_TICKETS
    assert len(created) == Planfile.MAX_BULK_TICKETS


def test_sprint_generator_limits_tickets_by_priority():
    generator = SprintGenerator()
    issues = [
        SimpleNamespace(
            title=f"Issue {i}",
            description="desc",
            priority="high",
            category="quality",
            file_path=f"file{i}.py",
            line_number=i,
            effort_estimate="1h",
            tags=[],
        )
        for i in range(generator.MAX_TICKETS_PER_PRIORITY + 20)
    ]

    issues += [
        SimpleNamespace(
            title=f"Issue {i}",
            description="desc",
            priority="low",
            category="quality",
            file_path=f"file{i}.py",
            line_number=i,
            effort_estimate="1h",
            tags=[],
        )
        for i in range(generator.MAX_TICKETS_PER_PRIORITY + 20)
    ]

    tickets = generator.generate_tickets({"issues": issues})

    total = sum(len(bucket) for bucket in tickets.values())
    assert len(tickets["high"]) == generator.MAX_TICKETS_PER_PRIORITY
    assert len(tickets["low"]) == generator.MAX_TICKETS_PER_PRIORITY