flowchart TD
    planfile__ci_runner["planfile.ci_runner<br/>10 funcs"]
    planfile__cli["planfile.cli<br/>8 funcs"]
    planfile__loaders["planfile.loaders<br/>12 funcs"]
    planfile__runner["planfile.runner<br/>8 funcs"]
    planfile__utils["planfile.utils<br/>5 funcs"]
    planfile__cli -->|3| planfile__loaders
    planfile__runner -->|2| planfile__utils
    planfile__cli -->|2| planfile__runner
    planfile__ci_runner -->|1| planfile__runner
