flowchart TD
    planfile__ci_runner["planfile.ci_runner<br/>10 funcs"]
    planfile__cli["planfile.cli<br/>22 funcs"]
    planfile__examples["planfile.examples<br/>45 funcs"]
    planfile__llm["planfile.llm<br/>7 funcs"]
    planfile__loaders["planfile.loaders<br/>21 funcs"]
    planfile__runner["planfile.runner<br/>8 funcs"]
    planfile__utils["planfile.utils<br/>8 funcs"]
    planfile__ci_runner ==>|22| planfile__examples
    planfile__cli ==>|4| planfile__loaders
    planfile__llm -->|3| planfile__examples
    planfile__runner -->|2| planfile__utils
    planfile__cli -->|2| planfile__runner
    planfile__cli -->|1| planfile__llm
    planfile__ci_runner -->|1| planfile__loaders
    planfile__ci_runner -->|1| planfile__runner
